name: Build windows

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: |
          MSBuild /p:Platform=x86 /p:Configuration=Release
          copy profanity.cl Release
          copy keccak.cl Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: Release/*